### ISSUE TITLE
v4 update

### ISSUE THREAD

**Issue by cyberwani** [jonathan-dejong/acf-pages-by-template#1]
Can you please update it to version 4.

**Comment by jonathan-dejong** [comment]
Hi Dinesh, 

I currently have no plans to update this to version 4. Since Elliot updated ACF it has become much simpler to create extra functionality on your own and my opinion is that this field no longer has enough value to be a custom field type.

I would rather see the addition of filtering the post_object field or/and relationship field with page templates much in the same way they can be filtered with post types and taxonomies. 

I could do this fork myself but at the moment I'm pretty busy with paying clients and projects and that has priority :)

**Comment by cyberwani** [comment]
Hi @jonathan-dejong,

Thanks for reply. It is appreciated if the more filters are available with the post_object.

BTW, I updated the plugin to version 4.
